RUN_NAME=rrg_v2_boot_0425_fix
JUDGE_MODEL=doubao-seed-2-0-lite-260215
TRAIN_FILES=data/rl/train.parquet
TEST_FILES=data/rl/test.parquet
TARJ_DATA_PATH=data/rl/traces_clean.json
BASE_MODEL=/home/liuguohong/.cache/modelscope/hub/models/Qwen/Qwen3-VL-8B-Instruct

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=rrg \
    algorithm.rrg.w_fact=1.0 \
    algorithm.rrg.w_reason=1.0 \
    algorithm.rrg.w_final=1.0 \
    algorithm.rrg.token_scale=24.0 \
    algorithm.rrg.alpha_fact_penalty=0.2 \
    algorithm.rrg.reason_length_penalty=0.3 \
    algorithm.rrg.final_judge_model=$JUDGE_MODEL \
    algorithm.rrg.rank_judge_model=$JUDGE_MODEL \
    algorithm.rrg.max_judge_workers=128 \
    algorithm.rrg.max_retries=5 \
    algorithm.rrg.debug_log=True \
    algorithm.rrg.debug_log_file=data/logs/$RUN_NAME.jsonl \
    reward_model.reward_manager=rrg \
    data.train_files=$TRAIN_FILES \
    data.val_files=$TEST_FILES \
    data.train_batch_size=8 \
    data.val_batch_size=8 \
    data.max_prompt_length=18432 \
    data.max_response_length=2048 \
    data.return_raw_chat=True \
    algorithm.rrg.judge_base_url=https://ark.cn-beijing.volces.com/api/v3 \
    actor_rollout_ref.model.path=$BASE_MODEL \
    actor_rollout_ref.actor.optim.lr=1e-5 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    +actor_rollout_ref.actor.fsdp_config.model_dtype=bf16 \
    +actor_rollout_ref.ref.fsdp_config.model_dtype=bf16 \
    actor_rollout_ref.rollout.dtype=bfloat16 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=16 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2 \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    +actor_rollout_ref.rollout.engine_kwargs.vllm.mm_processor_cache_gb=0 \
    actor_rollout_ref.rollout.n=1 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.ref.fsdp_config.param_offload=False \
    env.env_name=rrg \
    env.seed=42 \
    env.max_steps=0 \
    env.rollout.n=2 \
    env.rrg.trajectory_data_path=$TARJ_DATA_PATH \
    env.rrg.reasoning_history_length=5 \
    trainer.total_epochs=2 \
    trainer.project_name=rrg_training \
    trainer.experiment_name=$RUN_NAME \
    trainer.logger='["console", "swanlab"]' \
    trainer.n_gpus_per_node=8 \
    trainer.val_before_train=False \
    trainer.save_freq=10
