#!/usr/bin/env python3
"""Emit verl-shaped train/val parquets from an RRG task_root.

The verl pipeline uses ``data.train_files`` (a parquet) purely as a row-of-batch
scheduler — the actual rollout content is loaded by RRGReplayVecEnv from
``env.rrg.train_task_root`` at run time. The parquet therefore only needs the
columns:

  data_source : str
  prompt      : list[dict(role, content)]   (placeholder; managed by env)
  images      : list[dict(bytes, path)]     (placeholder bytes; managed by env)
  ability     : str
  extra_info  : struct(split, index, task_id, env_id, gold, schema)

The shape mirrors the 4-row smoke demo at /root/data/verl-agent/rrg/train.parquet
so that downstream RL code (which reads prompt / images back) finds a familiar
layout.

Usage::

    /root/verl-agent/.venv/bin/python scripts/prep_rrg_aug_parquet.py \
        --task_root /root/verl-agent/data/rrg-train-aug-combined \
        --out_dir /root/data/verl-agent/rrg \
        --min_rows 16          # repeat rows if fewer tasks than threshold
        --max_rows 10000

Re-running is idempotent — existing output files are overwritten.
Tasks whose screenshots are missing on the local box are skipped (the parquet
won't include them) so only runnable rows end up in the parquet.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd


# Placeholder image bytes: a REAL valid JPEG, generated by PIL.
# The actual frame content is loaded by RRGEnvironmentManager._load_img from
# ``fr["image_path"]`` at run time — verl never decodes these placeholder bytes,
# but verl's RLDataLoader still calls process_image() on them at batch assembly
# time. Two constraints on the placeholder:
#   1. PIL must accept it (a hand-crafted header is fragile; use PIL itself).
#   2. transformers' image_transforms.rescale flags any tensor where the
#      smallest two dims are equal as "channel dimension ambiguous" — so the
#      image must NOT be square (and ideally both H, W > 1). 14x14 grey works:
#      large enough that H != W and min(H,W) > 1, small enough that the bytes
#      don't bloat the parquet.
def _make_placeholder_jpeg() -> bytes:
    from io import BytesIO
    from PIL import Image
    buf = BytesIO()
    # Non-square (H != W) and both > 1 — guarantees transformers' rescale
    # won't flag the channel dimension as ambiguous.
    Image.new("RGB", (16, 14), color=(128, 128, 128)).save(buf, format="JPEG", quality=50)
    return buf.getvalue()


PLACEHOLDER_JPEG = _make_placeholder_jpeg()


def load_runnable_tasks(task_root: Path) -> list[dict]:
    """Filter tasks.json to those whose ALL step images exist on disk.

    Mirrors ``agent_system/environments/env_package/rrg/envs.py::_load_rrg_episodes``:
    same JSON structure, same path-resolution semantics (``root / s["image"]``).
    Returns a list of ``{"env_id", "task_id", "key", "goal", "gold", "schema",
    "n_steps", "task"}`` dicts with the data the parquet row needs.
    """
    tasks_json = json.loads((task_root / "tasks.json").read_text(encoding="utf-8"))
    schema_cache = json.loads((task_root / "params_cache.json").read_text(encoding="utf-8"))

    # Lazy import — keeps this script runnable without the agent_system env package.
    sys.path.insert(0, str(task_root.parent.parent))  # /root/verl-agent on path
    from agent_system.environments.env_package.rrg import answer_recovery as A

    gold_csv = A.auto_gold_csv(task_root)

    out = []
    skipped_missing_img = 0
    skipped_no_gold_schema = 0
    for t in tasks_json:
        env_id = str(t["env_id"])
        tid = t.get("task_id")
        key = f"{env_id}-{tid}"
        row = A._csv_row(gold_csv, env_id, tid)
        goal, _lang = A.resolve_goal_and_lang(row, t.get("task"))
        gold = A.load_gold(gold_csv, env_id, tid)
        schema = schema_cache.get(f"{env_id}:{tid}")
        if not (goal and gold and schema):
            skipped_no_gold_schema += 1
            continue

        all_imgs_present = all(
            (task_root / s["image"]).is_file() for s in t.get("steps", [])
        )
        if not all_imgs_present:
            skipped_missing_img += 1
            continue

        out.append({
            "env_id": env_id,
            "task_id": tid,
            "key": key,
            "goal": goal,
            "gold": gold,
            "schema": schema,
            "n_steps": len(t.get("steps", [])),
            "task": t.get("task", goal),
        })
    print(f"  total tasks in tasks.json        : {len(tasks_json)}")
    print(f"  skipped (no goal/gold/schema)    : {skipped_no_gold_schema}")
    print(f"  skipped (missing screenshot)     : {skipped_missing_img}")
    print(f"  runnable                          : {len(out)}")
    return out


def build_rows(tasks: list[dict], min_rows: int, max_rows: int) -> list[dict]:
    """Build verl-shaped parquet rows.

    Each task contributes one row (not per-step — verl's batch scheduler uses rows
    as grouping units; the env replays the full trajectory per row). We repeat the
    task list to reach ``min_rows`` (up to ``max_rows``).
    """
    if not tasks:
        raise SystemExit("No runnable tasks — cannot build parquet.")

    rows = []
    # Replicate to hit min_rows; cap at max_rows to keep file size in check.
    target = min(max(len(tasks), min_rows), max_rows)
    idx = 0
    while len(rows) < target:
        t = tasks[idx % len(tasks)]
        rows.append(_make_row(t, idx))
        idx += 1
    return rows


def _make_row(t: dict, index: int) -> dict:
    """Single verl-shaped row for a task."""
    return {
        "data_source": "rrg",
        "prompt": [{"role": "user", "content": "<image>"}],  # placeholder; env overwrites
        "images": [{"bytes": PLACEHOLDER_JPEG, "path": None}],  # placeholder; env overwrites
        "ability": "agent",
        "extra_info": {
            "split": "train",
            "index": index,
            # extras consumed by RRGEnvironmentManager via env wiring
            "task_id": t["key"],
            "env_id": t["env_id"],
            "tid": t["task_id"],
            "n_steps": t["n_steps"],
            # gold/schema are dicts — JSON-serialize so they round-trip cleanly.
            "gold": json.dumps(t["gold"], ensure_ascii=False),
            "schema": json.dumps(t["schema"], ensure_ascii=False),
            "goal": t["goal"],
        },
    }


def write_parquet(rows: list[dict], out_path: Path, split: str) -> None:
    """Write rows to a parquet at out_path. Wraps the columns in the structure that
    verl's HuggingFace-style loader expects (matches the existing demo schema).
    """
    # The columns 'data_source' / 'prompt' / 'images' / 'ability' must be wrapped
    # in Arrow lists/structs in the same shape as the demo parquet.
    import pyarrow as pa
    import pyarrow.parquet as pq

    data_source = pa.array([r["data_source"] for r in rows], type=pa.string())
    ability = pa.array([r["ability"] for r in rows], type=pa.string())

    prompt = pa.array(
        [r["prompt"] for r in rows],
        type=pa.list_(pa.struct([("role", pa.string()), ("content", pa.string())])),
    )
    images = pa.array(
        [r["images"] for r in rows],
        type=pa.list_(pa.struct([("bytes", pa.binary()), ("path", pa.string())])),
    )

    # extra_info: split, index, then task metadata. gold/schema are dicts
    # (JSON Schema for schema, partial answer dict for gold) so we serialize
    # them as JSON strings — round-trippable, matches verl's "non_tensor_batch"
    # convention for arbitrary metadata.
    extra_info = pa.array(
        [r["extra_info"] for r in rows],
        type=pa.struct([
            ("split", pa.string()),
            ("index", pa.int64()),
            ("task_id", pa.string()),
            ("env_id", pa.string()),
            ("tid", pa.string()),
            ("n_steps", pa.int64()),
            ("gold", pa.string()),
            ("schema", pa.string()),
            ("goal", pa.string()),
        ]),
    )

    table = pa.Table.from_arrays(
        [data_source, prompt, images, ability, extra_info],
        names=["data_source", "prompt", "images", "ability", "extra_info"],
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    pq.write_table(table, str(out_path))
    print(f"  wrote {out_path}  rows={len(rows)}  split={split}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--task_root", type=Path, required=True,
                    help="RRG task root directory (with tasks.json, rrg-source.csv, params_cache.json)")
    ap.add_argument("--out_dir", type=Path, required=True,
                    help="Output directory for train.parquet / val.parquet")
    ap.add_argument("--min_rows", type=int, default=16,
                    help="Minimum parquet rows; tasks replicated to reach this")
    ap.add_argument("--max_rows", type=int, default=10000,
                    help="Cap parquet rows to bound file size")
    ap.add_argument("--val_frac", type=float, default=0.1,
                    help="Fraction of unique tasks held out for validation")
    args = ap.parse_args(argv)

    print(f"[prep] task_root = {args.task_root}")
    print(f"[prep] out_dir   = {args.out_dir}")
    print()
    print("[prep] loading runnable tasks (those with all step-images on disk)…")
    runnable = load_runnable_tasks(args.task_root)
    if not runnable:
        print("[prep] ERROR: no runnable tasks. Check screenshot paths.", file=sys.stderr)
        return 1

    # Split deterministically: first val_frac hold out for val.
    val_n = max(1, int(round(len(runnable) * args.val_frac))) if len(runnable) >= 5 else 0
    val_tasks = runnable[:val_n]
    train_tasks = runnable[val_n:]
    print(f"\n[prep] split: {len(train_tasks)} train tasks, {len(val_tasks)} val tasks\n")

    print("[prep] building train rows…")
    train_rows = build_rows(train_tasks, min_rows=args.min_rows, max_rows=args.max_rows)
    train_out = args.out_dir / "train_aug.parquet"
    write_parquet(train_rows, train_out, split="train")

    if val_n > 0:
        print("[prep] building val rows…")
        val_rows = build_rows(val_tasks, min_rows=max(2, args.min_rows // 4), max_rows=args.max_rows)
        val_out = args.out_dir / "val_aug.parquet"
        write_parquet(val_rows, val_out, split="val")
    else:
        print("[prep] skipped val parquet (need ≥5 tasks for held-out split)")

    # Print schema summary so caller can sanity-check.
    print(f"\n[prep] done. parquets under {args.out_dir}:")
    for p in sorted(args.out_dir.glob("*_aug.parquet")):
        print(f"  {p}  ({p.stat().st_size / 1024:.1f} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
